name: Build and Release DigTool

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opencv-python numpy Pillow keyboard pywin32 ahk pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name=DigTool --icon=assets/icon.ico --add-data="assets;assets" --add-data="ui_components.py;." --add-data="utils.py;." --add-data="settings.py;." main.py

    - name: Create release package
      run: |
        mkdir release
        copy dist\DigTool.exe release\
        copy README.md release\
        copy LICENSE release\ 2>nul || echo "No LICENSE file found"

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: DigTool-Windows
        path: release/

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version || github.ref_name }}
        name: DigTool
        body: |
          Built on ${{ github.run_date }} with Pyinstaller
        files: |
          release/DigTool.exe
          release/README.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-build:
    runs-on: windows-latest
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opencv-python numpy Pillow keyboard pywin32 ahk pyinstaller

    - name: Test build
      run: |
        pyinstaller --onefile --windowed --name=DigTool --icon=assets/icon.ico --add-data="assets;assets" --add-data="ui_components.py;." --add-data="utils.py;." --add-data="settings.py;." main.py

    - name: Upload test build
      uses: actions/upload-artifact@v3
      with:
        name: DigTool-Test-Build
        path: dist/DigTool.exe
        retention-days: 7